# Generated by Django 4.2.7 on 2024-02-02 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistitem',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
