# Generated by Django 4.2.7 on 2024-02-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_content_todolistitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistitem',
            old_name='name',
            new_name='title',
        ),
    ]
