# Generated by Django 4.2.7 on 2024-02-08 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_alter_todolistitem_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
