# Generated by Django 4.2.7 on 2024-02-08 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_todolistitem_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
