# Generated by Django 4.2.7 on 2024-02-08 14:48

from django.db import migrations, models
import todoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_alter_todolistitem_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='due_date',
            field=models.DateTimeField(default=todoapp.models.one_week_hence),
        ),
    ]
