# Generated by Django 5.0.1 on 2024-02-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0013_todolistitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='owner',
        ),
    ]
