# Generated by Django 5.0.2 on 2024-03-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0019_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='todo_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todoapp.todolist'),
            preserve_default=False,
        ),
    ]
