databases:
  - name: todoListProjectdb
    plan: free
    databaseName: todoListProject
    user: todoListProject

services:
  - type: web
    plan: free
    name: todoListProject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn todoListProject.asgi:application -k uvicorn.workers.UvicornWorker" envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todoListProjectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
