databases:
  - name: todoprojectdb
    plan: free
    databaseName: todoproject
    user: todoproject

services:
  - type: web
    plan: free
    name: todoproject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn todoproject.gggasgi:application -k uvicorn.workers.UvicornWorker" 	
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todoprojectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
